bases:
- ../../../deploy-config/default
- ../../../pattern-config/dev
- ../../../deploy-config/hpa
commonLabels:
  app: msa02
  project: msatest
configMapGenerator:
- literals:
  - SPRING_CONFIG_LOCATION=classpath:/,classpath:/config/,file:/,file:/pattern/dbaccess.yaml,file:/pattern/messagechannel.yaml,file:/pattern/session.yaml,file:/pattern/cache.yaml,file:/pattern/metric.yaml,file:/pattern/log.yaml,file:/config/,file:/config/application-overlay.yaml
  name: system-config
- files:
  - application-overlay.yaml
  name: app-config
images:
- name: cloudsvcdev/microservice
  newName: vup-registry.cloudzcp.io/modern/example/msa02
  newTag: 0.0.1
namePrefix: msa02-
nameSuffix: -msa02
patchesJson6902:
- path: service-patch.yaml
  target:
    kind: Service
    name: app
    version: v1
patchesStrategicMerge:
- replicas-patch.yaml
- imagepolicy-patch.yaml
- spec-patch.yaml
- hpa-patch.yaml
